data_root_dir: "datasets/open-x-embodiment"
run_root_dir: "runs" 
adapter_tmp_dir: "checkpoints"
learning_rate: 2e-5 
use_llm_lora: False 
use_backbone_lora: False 

 
save_steps: 400
wandb_project: "openvla"
wandb_entity: ""
save_latest_checkpoint_only: False
